title: "TC6D Manifesto v1.0"
description: "Ensaio Filosófico-Matemático sobre a Estrutura de Campo da Realidade"
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/reasoningbyfigueiredo/tc6d-manifesto
